### ISSUE TITLE
Healthcheck/Ping/Status endpoint

### ISSUE THREAD

**Issue by ruant** [vippsas/vipps-ecom-api#101]
Would be really nice to have a Healthcheck/Ping/Status endpoint to be able to test that a connection can be made to the API with the current credentials.

**Comment by cloveras** [comment]
Hi @ruant 

Yes, we agree, but the best ewr have for now is the Statuspage: 
Production: https://vipps.statuspage.io
Test: https://vipps-test.statuspage.io

If you just want to check your API credentials, you can try to initiate an order, then let it expire, or actively cancel it. 

Christian, Vipps

**Comment by cloveras** [comment]
Hi @ruant 

Is it OK to close this issue? I know we don't have the endpoint, but with Statuspage x 2 and a quite simple way to check credentials (initiate + cancel), I hope it can work for you as it is?

Christian, Vipps
