### ISSUE TITLE
Cancelled payment

### ISSUE THREAD

**Issue by piotrczyz** [vippsas/vipps-ecom-api#103]
When I cancel a payment on this screen than I don't get any `TransactionLogHistory `with "Cancel" PaymentOperation while calling` /ecomm/v2/payments/{orderId}/details` endpoint.

![2020-04-10 20_52_22-Chat _ Microsoft Teams](https://user-images.githubusercontent.com/735432/79015541-3dff1380-7b6d-11ea-9109-e36adc3e3622.png)

![image](https://user-images.githubusercontent.com/735432/79015958-270cf100-7b6e-11ea-8b4f-3c57f3703cbf.png)

It works when I cancel either before I provide a phone number or in the Vipps test app.
 
![image](https://user-images.githubusercontent.com/735432/79015857-f3ca6200-7b6d-11ea-8aed-a2fd4fb97f84.png)

Any ideas why?

**Comment by tht13** [comment]
Hi @piotrczyz please email your issue to integration@vipps.no and we will assist you further 😄 
From what I see from initial investigation is you should be getting a Cancel status on that first transaction, but we will have to investigate this further.
