### ISSUE TITLE
Refund errorCode - wrong type

### ISSUE THREAD

**Issue by asamofal** [vippsas/vipps-ecom-api#104]
Hi!
If try to refund more than captured amount an error will be returned _(as expected)_, but `errorCode` set as string.
In all other cases `errorCode` returned as integer.

```
[
  {
     "errorGroup":"Payment",
     "errorCode":"71",
     "errorMessage":"Can't refund more than captured amount",
     "contextId":"cd391e18-2e88-43ef-b540-d841deb1db20"
  }
]
```

I think will be better for consistency to use the same type everywhere.

**Comment by tht13** [comment]
Hi, can you provide an example of errorCode being of type Integer, it should always be String.

**Comment by cloveras** [comment]
Hi @asamofal 

We have checked the code, and all error codes are strings. @tht13 also tested this to make sure.

We may of course have overlooked something, so if you have additional information, that would be helpful.

Christian, Vipps

**Comment by asamofal** [comment]
@tht13 @cloveras Sorry, guys, it was misunderstanding from my side. I've noticed error handler in our project where other errorCodes were catching as integers and I decided that all errorCodes must be integers (in fact it was a mistake in our error handler).

Thanks for quick answer!

**Comment by cloveras** [comment]
Hi @asamofal 

No problem - good to hear it worked out!

Christian, Vipps
