### ISSUE TITLE
Callback statuses different in Swagger and markdown documentation

### ISSUE THREAD

**Issue by bruun** [vippsas/vipps-ecom-api#110]
According to [the markdown docs](https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#callback-statuses), the following are valid transaction statuses in the callback: `RESERVED, SALE, RESERVE_FAILED, SALE_FAILED, CANCELLED, REJECTED`

In [the Swagger docs](https://vippsas.github.io/vipps-ecom-api/#/Endpoints%20required%20by%20Vipps%20from%20the%20merchant/transactionUpdateCallbackForRegularPaymentUsingPOST), the following are valid statuses: `RESERVE, SALE, CANCELLED, REJECTED, AUTO_CANCEL`

Some overlap, others are either missing in one or the other, or spelled differently (`RESERVE` vs `RESERVED`). 

Am I mixing up what the callback statuses in the markdown docs are referring to, or is one of the documentations incorrect?

**Comment by cloveras** [comment]
Hi @bruun 

Thanks for reporting this.

We do, unfortunately, have some tech debt here and there, and the varying ways of spelling states is one of them. I'm sorry.

We will have a look at this ASAP, and either correct the mistakes, or make it clearer that "tis is how it is".

Christian, Vipps

**Comment by ruant** [comment]
I think that this issue should be reopened, or atleast revisisted by the team.
@cloveras @niklud 

Still kinda unclear regarding the Callback statuses:
![image](https://user-images.githubusercontent.com/1150473/90513641-40e3c380-e160-11ea-8de8-4e8d4f204e0f.png)

Swagger docs say `Example: RESERVE`
But the Enums say something completly different
`Enum:[ RESERVED, SALE, CANCELLED, REJECTED, AUTO_CANCEL, SALE_FAILED, RESERVE_FAILED ]`

https://github.com/vippsas/vipps-ecom-api/commit/493b51a3a5c68ce08559eac7fada997b7991c48a#diff-3933d49df39e665e1db0e420518b7c20R1100
https://github.com/vippsas/vipps-ecom-api/commit/493b51a3a5c68ce08559eac7fada997b7991c48a#diff-3933d49df39e665e1db0e420518b7c20R1112

**Comment by niklud** [comment]
Sorry, seems like I forgot the example when making those changes. Should have been fixed now. Please tell me if you find anything else.
