### ISSUE TITLE
Call to merchant app Fallback URL not initiated while pay with vipps prompt for Pin.

### ISSUE THREAD

**Issue by Anilkbalakrishnan** [vippsas/vipps-ecom-api#127]
Hi Tema, I am integrating payment with vipps to an iOS App and what I have noticed in a particular scenario is that, after making payment in vipps, the Vipps app is not invoking the fallback url to deep link back to the merchant app. 

I am initiating the vipps payment with the parameter "isApp": true to perform deeplinking with app and this issue happens for a particular scenario explained below.

The flow works as expected for vipps initiate payment with the required details, and I get the deeplinking url to open the vipps app successfully to prompt for the payment. so far no problem. 
But  when you tap on pay some times vipps app prompts to enter pin. In this specific case when it prompts to enter pin, if you enter pin the payment is successful but it will not invoke or open the fallback url to deeplink back to the customer app to poll for status. Also noticed in this scenario, even though the payment is shown successful in vipps app, vipps is also not invoking the call-back url to notify the status as reserved to the backend. This is causing an bad experience to the user who pays in vipps.

I face this in Merchant Test app and  would like to know if this can be fixed be at your end before I switch my configuration to production and make live payments.

**Comment by cloveras** [comment]
Hi @Anilkbalakrishnan 

Thanks for reporting this.

Can you please port the full HTTP request for the payment initiation (you can hide the client_secret and subscription key, and truncate the auth header).

Christian, Vipps

**Comment by Anilkbalakrishnan** [comment]
Hi @cloveras 

I can do that, But I am Just curious what are you specifically looking for in payment Initiation request? The reason being normally (in most of the time) there is no problem with the initiate payment or making payment successfully in vipps app. 

The issue I raised is for a specific scenario mentioned below. 
when you have not opened vipps MT app for a while (may be a day or two).
Then when you try to Pay with vipps from any client app you were able to successfully deeplink to vipps app and show the payment info.
Now  when you tap pay in vipps. "I have been prompted to enter 4 digit pin ". 
Scenario:
In this scenario where when you tap on pay on vipps app and if vipps app prompt you to enter 4 digit pin. if you enter the pin correctly the payment will be success in vipps app. but the vipps app is not invoking the deep linking fallback url  also there is no updates sent to the callbackurl.

For security reason: I cannot post the callback url and fallback url that I pass to the the payment initiate request. 

All I suspect is the Vipps iOS app on payment initiate form any other app, if it prompts for pin while tap on pay.  some one from iOS need to verify if its invoking the fallback url form iOS app and also need to verify if its invoking the callback url.


here is the Json request with mock info 

{
	“customerInfo”: {
	},
	“merchantInfo”: {
		“merchantSerialNumber”: “{{ merchant_serial_num  }}“,
		“callbackPrefix”: “https://example.com/XXXXXXXXXXX”,
		“fallBack”: “XXXX:XXXXX?orderid=212366-1C06ACED-BA5E”,
		 “isApp” : true
	},
	“transaction”: {
		“orderId”: “order12xd3adbdcddddd”,
		“amount”: 100,
		“transactionText”: “One pair of Vipps socks”
	}
}


Thanks and Regards,
Anil K Balakrishnan

**Comment by cloveras** [comment]
Hi

Thanks for the additional info.

Were you using your own (dedicated) test user, or the "common" test user? 

We think there may have been a problem with the common test user, and we now recommend all customers to only use their dedicated test user.

Christian, Vipps

**Comment by Anilkbalakrishnan** [comment]
HI @cloveras,

Thanks for the update. Actually I am using the common test user. let me see if I face the same issue with the dedicated test user.

Thanks and Regards.
Anil K Balakrishnan

**Comment by cloveras** [comment]
Hi @Anilkbalakrishnan 

I have deleted the common test user from the documentation now. It is not needed, as all customers have their own dedicated test user.

Christian, Vipps
