### ISSUE TITLE
Localhost as fallback crept up again

### ISSUE THREAD

**Issue by CraigAndrew** [vippsas/vipps-ecom-api#135]
This  https://github.com/vippsas/vipps-ecom-api/issues/98 issue is happening again on VIPPS Test Environment.
Getting a 400 response for my requests with error:
{
"errorGroup": "Merchant",
"errorCode": "Invalid IP address",
"errorMessage": "Invalid IP address",
"contextId": "ed9f848e-8a76-4d66-ac75-c1df9d011fa3"
}

when the URLs in the request start with http://127.0.0.1
e.g: http://127.0.0.1/vipps/payment/done/123

I'm familiar with getting it working as I have the same URL working fine for Recurring API but not for ECommerce API

**Comment by cloveras** [comment]
Hi

Thanks for reporting this. We will check and send an update ASAP. 

Christian, Vipps

**Comment by CraigAndrew** [comment]
@cloveras any update?

**Comment by webmaeistro** [comment]
use ngrok to generate a public url thats funneld to your localhost. Vipps cannot deal with localhost/127.0.0.1 urls (somewhat answering quickly here but according to the docs thats my understanding)

**Comment by cloveras** [comment]
Hi

Sorry for the super late response.

Our documentation for the Vipps eCom API v2 specifies that URLs must validate with the Apache Commons UrlValidator, and also:

> URLs that start with https://localhost will be rejected. If you want to use localhost as fallback, please use http://127.0.0.1. It is, naturally, not possible to use https://localhost or http://127.0.0.1 for the callback, as the Vipps backend would then call itself

Are there some places in the documentation where this is not clear? And if so: Can you please give some specific examples of requests that give an error response?

Christian, Vipps

**Comment by cloveras** [comment]
Closing..
