### ISSUE TITLE
Backward compatibilty

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-ecom-api#15]
Api v1 should be available when moving to v2 using same auth keys.

Its a bit frustrating moving to v2 with regularly and breaking changes from v1 without having the stable functionality which was working in v1.

Having v1 also available in v2 would fix this and could let us play around with v2 until its stable while using v1 for public applications.

**Comment by cloveras** [comment]
Hi!

Sorry for the late answer.

We are aware that multiple auth keys is not ideal, and we have it in our backlog to have the same keys across API - but it is not prioritized. Using the same key across multiple _current_ APIs is likely to come before older versions of APIs. 

Christian, Vipps
