### ISSUE TITLE
Fallbackurl does not work with localhost for apitest - merchantInfo.fallBack.invalid

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-ecom-api#159]
**Description:**
It is a bit frustrating that localhost cannot be used as fallback url for development, as this is normally how developers are testing the workflow.

Replacing `http://localhost:8080/vipps` with `http://example.com/vipps` lets the request through, but using localhost does not work with any ports.

**Endpoint:** https://vippsas.github.io/vipps-ecom-api/shins/index.html#initiate-payment

**Request**:
```json
{
  "merchantInfo": {
    "merchantSerialNumber": "{{merchantSerialNumber}}",
    "callbackPrefix":"https://example.com/v1/callback/vipps",
    "fallBack": "http://localhost:8080/vipps",
    "isApp":false
  },
  "customerInfo": {
    "mobileNumber": "{{mobileNumber}}"
  },
  "transaction": {
    "orderId": "{{orderId}}",
    "amount": {{amount}},
    "transactionText": "{{transactionTextInitiate}}",
    "skipLandingPage": false
}
}
```

**Error msg:**
```json
[
    {
        "errorGroup": "Merchant",
        "errorCode": "merchantInfo.fallBack.invalid",
        "errorMessage": "Invalid fallback URL",
        "contextId": "7ba66420-6ead-404f-831c-7518f02a4bee"
    }
]
```

Ref: https://github.com/vippsas/vipps-ecom-api/issues/53

**Comment by cloveras** [comment]
Hi

Can you use 127.0.0.1, as documented here?

https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#url-validation

Christian, Vipps

**Comment by steffanhalv** [comment]
> Hi
> 
> Can you use 127.0.0.1, as documented here?
> 
> https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#url-validation
> 
> Christian, Vipps

Thanks, that is an ok workaround for fallback.
But I don't see why localhost is blocked as localhost is the most common url for developers.

It would be nice if you can make an update for this :)

(I understand callback though, as it cannot be reached by your servers).
Btw. in the docs you are linking to https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/UrlValidator.html which does not include the validation config. Perhaps you should replace it with this:
https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#url-validation

Thanks anyway, this will work for our use case.

**Comment by cloveras** [comment]
Hi @steffanhalv 

Sorry for the super late reply.

We're trying to keep the test and productionnenvironments similar, and since 127.0.0.1 works, we will leave this as it is.

I also added a tip about Ngrok: https://github.com/vippsas/vipps-ecom-api/commit/ca1272699e4f9b927257ea923a3e7cee4e14cb28

Christian, Vipps

**Comment by cloveras** [comment]
Hi again

I don't understand your comment abouyt the UrlValidator. Do you mean that we shoyld link to ourselves? 

We try to make it easy to undertand how we do our validation, and also offer a code example. The error messages have also been improved, so it :should_ (🤞) be straight-forward to understand which URLs are valid. 

Christian, Vipps

**Comment by steffanhalv** [comment]
I ment that it should be linked to https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#url-validation from here -> https://vippsas.github.io/vipps-ecom-api/shins/index.html#initiate-payment and not only the protocol. Anyway, I think this issue can be closed after that...

;)

**Comment by cloveras** [comment]
Hi @steffanhalv

Thanks for your contribution to make the Vipps development experience better!

As mentioned in our newsletter, we would like to send you a pair of Vipps socks: https://github.com/vippsas/vipps-developers/blob/master/newsletters/2021-02-newsletter.md#suggest-improvements-get-a-pair-of-vipps-socks-

Can you please send us your mail address? Send an email to integration@vipps.no with subject “Socks”.

Thanks!
Vipps Integration

**Comment by cloveras** [comment]
Hi @steffanhalv 

I have fixed the URL validation link now, it will be in the next merge: https://github.com/vippsas/vipps-ecom-api/pull/184/commits/951fcaa370dd84460f3cc9a1315e0831f6f8c7ae

Thanks!

Christian, Vipps
