### ISSUE TITLE
Change to utf8-encoding on checkout.

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-ecom-api#16]
Æ Ø Å not rendered on checkout page, please fix.

![skjermbilde 2018-08-16 kl 13 12 42](https://user-images.githubusercontent.com/4593184/44205326-431c7d00-a156-11e8-9053-034b10ed5091.png)

**Comment by alfmags** [comment]
Thanks for the issue, will investigate and forward! :)

**Comment by alfmags** [comment]
The fix is now being tested, should go live soon.

**Comment by aridder** [comment]
The fix is now live. Thank you for reporting the issue, @steffanhalv
