### ISSUE TITLE
Fallback 'INTENT' on iOS opens up browser with url: 'intent' (App integration - Vipps)

### ISSUE THREAD

**Issue by Remi749** [vippsas/vipps-ecom-api#164]
Hi, I tried following the steps shown in https://www.vipps.no/developers-documentation/ecom/documentation/#app-switching

> Redirect back to merchant app by simply closing the Vipps app
> With this approach, the merchant app does not have to register/handle deeplink urls.
> 
> In order to use this approach, when creating the payment in the merchant has to pass fallback attribute like this:
> 
> "fallBack": "INTENT"
> 
> (and only "INTENT"", no parameters etc.)
> 
> This will cause the Vipps app to simply close after a successful or canceled ecom payment, and fall back to the calling merchant app.

Fallback 'INTENT' on iOS opens up browser with url: 'https://intent/?status=202', any ideas as to why? 

This is not the case for Android, here the app switches back to my app.

**Comment by thomanil** [comment]
Hi,

the fallback = "INTENT" mechanism for switching back is an Android-only feature (it's under the Android section but not present in the iOS section in the docs), so unfortunately you can't use it across the board. 

So: both versions support using fallback="https:// or yourscheme://" to actively deeplink back to your own app, while only the android app supports "falling back to the last app" via fallback="INTENT"

**Comment by Remi749** [comment]
@thomanil 
thanks for the reply. So if I understand the fallback correctly for iOS, i have to just add: "myapp://" to fallback to my app?

**Comment by thomanil** [comment]
To deeplink back into your own iOS native app: yes.
