### ISSUE TITLE
Swagger merchantSerialNumber regex not correct

### ISSUE THREAD

**Issue by Deltids** [vippsas/vipps-ecom-api#174]
It says in the docs that the merchantSerialNumber should be defined like this:

```
merchantSerialNumber* | string
minLength: 6
maxLength: 6
example: 123456
pattern: ^\d{6}$
```

Our company's msn is a 5 numbered number. Should it be prefixed in some way (update docs), or is the constraint wrong (update docs)?

**Comment by cloveras** [comment]
Hi @Deltids 

You're right. Old MSNs were five digits.

Fixed in https://github.com/vippsas/vipps-ecom-api/commit/ecfc1cf441abf916bd7d9208e8d76110f7d2acc7

Christian, Vipps

**Comment by cloveras** [comment]
Hi @Deltids 

Thanks for your contribution to make the Vipps development experience better!

As mentioned in our newsletter, we would like to send you a pair of Vipps socks: https://github.com/vippsas/vipps-developers/blob/master/newsletters/2021-02-newsletter.md#suggest-improvements-get-a-pair-of-vipps-socks-

Can you please send us your mail address? Send an email to integration@vipps.no with subject “Socks”.

Thanks!
Vipps Integration
