### ISSUE TITLE
Cancelling PENDING charge returns error

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-ecom-api#181]
The issue looks very similar to https://github.com/vippsas/vipps-recurring-api/issues/111

`PUT https://apitest.vipps.no/ecomm/v2/payments/{id}/cancel`

gives

`500 APIM Internal Server Error - Something went wrong, please try again later.`

when charge is still PENDING

**Explanation:**
If customer goes to a webpage _(using a computer)_, buys a product & comes all the way to the app _(using mobile phone)_ where the last step is to only click the 'Betal' button and skips to press the 'Betal' button, then goes back to the webpage, selects another product **which should be a REPLACEMENT of the first selected product**, initiates a new payment, the old payment is still visible in app.

The reason is because there is no way to cancel a PENDING charge as it gives error similar to what the recurring endpoint does.

**Comment by tht13** [comment]
Hi @steffanhalv 
Could you share the orderId this is causing an error on?
Or if this is considered sensitive please email me the details at thomas.haakon.townsend@vipps.no

**Comment by steffanhalv** [comment]
> thomas.haakon.townsend@vipps.no

Here you go:
https://apitest.vipps.no/ecomm/v2/payments/ord-27-t-1613557715/cancel

**Comment by tht13** [comment]
@steffanhalv could you provide the request header and body (mask and tokens)?

**Comment by cloveras** [comment]
Hi @steffanhalv 

Can you please send us some additional information? We do not log the complete requests in the production environbment, so to be able to find out what causes the error, we need a bit more info.

Christian, Vipps

**Comment by cloveras** [comment]
I did find something in our logs: `Query not loaded the merchant config limts ignoring the exception`. I don'rt know if it's relevant, so I have notified the Recurring team, hoping they can help.

**Comment by cloveras** [comment]
Hi @steffanhalv 

Thanks for your contribution to make the Vipps development experience better!

As mentioned in our newsletter, we would like to send you a pair of Vipps socks: https://github.com/vippsas/vipps-developers/blob/master/newsletters/2021-02-newsletter.md#suggest-improvements-get-a-pair-of-vipps-socks-

Can you please send us your mail address? Send an email to integration@vipps.no with subject “Socks”.

Thanks!
Vipps Integration
