### ISSUE TITLE
400 azure error, complains about my ID not being found in the tenant

### ISSUE THREAD

**Issue by Krisar95** [vippsas/vipps-ecom-api#183]
The error I'm getting:

```json
{
    "error":"unauthorized_client",
    "error_description":"AADSTS700016: Application with identifier \'my_client_id\' was not found in the directory \'tenant_directory\'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.",
    "error_codes":[700016],
    "timestamp":"2021-03-23 06:46:31Z",
    "trace_id":"xxx", 
    "correlation_id":"xxx",
    "error_uri":"https://login.windows.net/error?code=700016"
}
```
POST Request to: `/accesstoken/get`

The headers are properly formed, and I have quadruple checked all the keys. I am sending the keys in the HEADERS, to the test URL. From what I gather from your FAQ is that this error occurs when you send the wrong key to the wrong endpoint. I however do know with 100% certainty that these are the correct keys. This is also getting sent to the correct server (the test server).
Have I been banned or something? :smile:

**Comment by cloveras** [comment]
Hi @Krisar95 

Can you please try to make the same call with our Postman collection?

Christian, Vipps

**Comment by Krisar95** [comment]
Same thing happens using your postman collection.

**Comment by cloveras** [comment]
Which MSN (Merchant Serial Number) is this for?

**Comment by cloveras** [comment]
Does this help? https://github.com/MicrosoftDocs/azure-docs/issues/24673

**Comment by Krisar95** [comment]
> Which MSN (Merchant Serial Number) is this for?
> Which `client_id` are you using?
> Are you using apitest.vipps.no or api.vipps.no?

My MSN only get a client ID for apitest.vipps.no

**Comment by cloveras** [comment]
Ok, but:

Which MSN (Merchant Serial Number) is this for?
Which client_id are you using?
Are you using apitest.vipps.no or api.vipps.no?

**Comment by Krisar95** [comment]
> Ok, but:
> 
> Which MSN (Merchant Serial Number) is this for?
> Which client_id are you using?
> Are you using apitest.vipps.no or api.vipps.no?

MSN: `217509`
client_id: `01931a00-8486-4ba3-85f9-73de7fc66aoe`
server: `https://apitest.vipps.no`

**Comment by cloveras** [comment]
We can not see anything wrong on our side. Can you please try to explain as detailed as possible, where it goes wrong? Step by step, with the complete requests and responses as shown with "Inspect" in Postman (please mask secrets).

See: https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md#get-an-access-token

And: https://github.com/vippsas/vipps-developers/blob/master/postman-guide.md

**Comment by cloveras** [comment]
Hi @Krisar95 

Can you please give us some more details, so we can try to find out what's wrong?

Christian, Vipps

**Comment by Krisar95** [comment]
Sure thing.
I started out with python:
```py
import requests

vipps_url = "https://apitest.vipps.no/accesstoken/get"

# MSN does not appear to be required for this call, according to swagger
headers = {
    "client_id": "01931a00-8486-4ba3-85f9-73de7fc66aoe",
    "client_secret": "xxxxxxxxxxx",
    "Ocp-Apim-Subscription-Key": "xxxxxxxxxxx",
}

r = requests.post(vipps_url, headers=headers)

print(r.status_code)
print(r.content)
```
The above returns the error I opened this issue with.

![request](https://user-images.githubusercontent.com/58483513/112136533-5c6bec80-8bcf-11eb-9fb8-832b28e173fe.png)
![response body](https://user-images.githubusercontent.com/58483513/112136535-5d9d1980-8bcf-11eb-8263-91fe1c29a271.png)
![response headers](https://user-images.githubusercontent.com/58483513/112136537-5e35b000-8bcf-11eb-93bc-ef0ded340643.png)

**Comment by cloveras** [comment]
Thanks @Krisar95!

MSN 217509 seems correctly set up in our test environment ("MT"). We can not find any problems.

I assume you used both our Postman collection and environment, and followed the guide: https://github.com/vippsas/vipps-developers/blob/master/postman-guide.md

When you get the `unauthrized_client`response: Which API endpoint are you calling? 

Can you post the full URL that gives the error response? 

Christian, Vipps

**Comment by Krisar95** [comment]
Well, yes, I used both the collection and your environment.
I **POST** to `https://apitest.vipps.no/accesstoken/get` (A `GET` request returns a 404, not a 400)
And it returns the error I opened the issue with. Every time.

**Comment by cloveras** [comment]
Hello again!

Ok, so: You are absolutely 100 % sure you are using the *test* API credentials for MSN 217509 in the *test* environment.
And you make this API call to try to get the access token:

```
POST https://apitest.vipps.no/accesstoken/get
client_id: 01931a00-8486-4ba3-85f9-73de7fc66aoe
client_secret: <not shown or known>
Ocp-Apim-Subscription-Key: <not shown or known>
```

And then you get the `unauthorized_client` response. Hmmm!

We have looked at everything we can think of, but we can not find anything wrong on our side.

Coulds you try to turn the verboseness up to max for either HTTPie (https://httpie.io/docs#verbose-output) or curl (https://everything.curl.dev/usingcurl/verbose) and paste _everything_ here? Replace the `client_secret` with "XXX" and only include the first four(?) characters of the `Ocp-Apim-Subscription-Key`? 

I don't know what we can find, but that's mny best suggestion now.

Christian, Vipps

(Sorry about the whole `POST:/accesstoken/get`, but it does work, and we can't really replace it just because it's weird)

**Comment by cloveras** [comment]
I just found some strange things in our logs: GET requests for `/oauth2/auth` this morning at 23/Mar/2021:06:43:00 +0000, with the `client_id`, etc in the query string, and "user agent python-requests/2.22.0":

`GET /oauth2/auth?client_id=01931a00-8486-4ba3-85f9-73de7fc66aoe&client_secret=<removed>&Ocp-Apim-Subscription-Key=cceec<truncated> HTTP/1.1` 

I guess this was the first attempts mentioned in this issue.

Since you used your `client_secret` in plain text, you should regenerate it on portal.vipps.no.

I also found this:

```
properties: { [-] 
      action:  Matched 
      clientIp:  <removed>
      clientPort: 
      details: { [+] 
     } 
      hostname:  apitest.vipps.no 
      instanceId:  appgw_2 
      message:  SQL Injection Attack: Common Injection Testing Detected 
      policyId:  default 
      policyScope:  Global 
      policyScopeName:  Global 
      requestUri:  /accesstoken/get 
      ruleId:  942110 
      ruleSetType:  OWASP_CRS 
      ruleSetVersion:  3.0.0 
      site:  Global 
      transactionId:  <removed> 
   } 
```

Does that tell you anything?

**Comment by cloveras** [comment]
I also found several more hits for your client_id in our logs, where our systems report hits for rules like:
* Detects MySQL comment-/space-obfuscated injections and backtick termination 
* Detects basic SQL authentication bypass attempts 2/3 
* Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (12)

**Comment by cloveras** [comment]
I'm checking with my colleagues if this means anything for your API calls, or if it's just normal logging of standard checks we always do.

**Comment by Krisar95** [comment]
That would make sense actually. At 6AM this morning I was just trying this and that, beating my head against a wall when trying to call your API in many different ways... Didn't occur to me that it would trigger some sort of security response.
That probably happened because I tried to pass my `client_id` as a parameter. Your logger picked that up as a SQL injection attempt... Rest assured I was absolutely not trying to perform any sort of attack on your systems. I didn't think anything of it, mostly because in most cases these things are escaped and sanitized before they're handled.

It's good to know that, though! I'll remember not to do that again.

**Comment by cloveras** [comment]
Your sale unit is not blocked in any way, you can check that on portal.vipps.no any time.

**Comment by Krisar95** [comment]
> Your sale unit is not blocked in any way, you can check that on portal.vipps.no any time.

:thinking: Strange. Curl request still don't work, they still throw that azure error. Perhaps you can show me what a properly formed request looks like and I can try to execute that? I must be doing something wrong somewhere then.

**Comment by cloveras** [comment]
Hi

Our Postman collection, the Swagger/OpenAPI files, the example code the documentation has properly formed requests.

Christian, Vipps

**Comment by Krisar95** [comment]
Hi
I wanted to reiterate:
I already tried the addon WPHosting-AS developed for woocommerce, that is recommended by Vipps. It's linked in your getting started guide. I assume that does in fact send valid requests. That still doesn't work, and returns the same error as listed in the beginning of this issue. `unauthorized_client`. It's even thrown as a special error message in the notice header of WordPress, on a different server, in a different country. I have verified many times that the problem is not local to my machine or the network I'm on. I'm at a loss, I don't know what to do. 

The only thing that's left to do is to ask you guys to set the account up again from scratch. New keys, new secrets.
On second thought: perhaps you can try to send the requests using my credentials?

Best,
Kristófer.

**Comment by Krisar95** [comment]
### Update
I regenerated all three keys. Issue resolved. Thanks for your help @cloveras 

Best,
Kristófer

**Comment by cloveras** [comment]
Good to hear that it worked out!

We never invalidate API keys, so this is indeed a mystery. 

At least this resulted in some improvements to our FAQ: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-faq.md#why-do-i-get-http-401-unauthorized

Christian, Vipps

**Comment by cloveras** [comment]
One last improvement: https://github.com/vippsas/vipps-ecom-api/commit/7b710099360df6433822d707cbcbd9a12e61fd1b

> If you are absolutely 100 % sure that you have done everything correctly,
> and it _still_ doesn't work, you can regenerate the API keys on
> [portal.vipps.no](https://portal.vipps.no).
> This should never be necessary, and we can not think of any situations where
> this fixes any known problem, so it's our very last suggestion.
> The old API keys will of course stop working when they have been regenerated.
