### ISSUE TITLE
Allow cancellation of charges before the transaction has been sent to the PSP

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-ecom-api#198]
**This endpoint:**
https://vippsas.github.io/vipps-ecom-api/#/Vipps%20eCom%20API/cancelPaymentRequestUsingPUT

**Returns this:**
```
Server error: `PUT https://apitest.vipps.no/ecomm/v2/payments/ord-10-t-1622723464/cancel` resulted in a `500 APIM Internal Server Error` response:
{"responseInfo":{"responseCode":500,"responseMessage":"Something went wrong, please try again later."}
```

Even before the phone number has been inserted.

**Short term solution:**
It should be possible to cancel a charge until the transaction has been sent to the PSP and if the transaction process has been started, the API should return information about the transaction is being processed by a third party PSP, not return 500 server error.

**Long term solution:**
A started transaction with the PSP should be reversible/'possible to abort' so a cancellation always will be possible until a charge has been completed.

**Refs.:** 
https://github.com/vippsas/vipps-ecom-api/issues/181
https://github.com/vippsas/vipps-recurring-api/issues/111

**Comment by cloveras** [comment]
Hi @steffanhalv 

Thanks for this, I've asked the team to have a look.

Christian, Vipps

**Comment by cloveras** [comment]
Hello again

Was the user in a 3D Secure session, btw? If so, the call will not succeed - as mentioned on https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#cancelling-a-pending-order

We should of course avoid 500 errors, so we will update here when we have more information.

**Comment by steffanhalv** [comment]
No, it was before even the phonenumber was inserted

**Comment by tht13** [comment]
@steffanhalv our backend logs show the body of this request is either NULL or at the very least not valid json, could you please check what you send in this request, the body is not optional.

**Comment by steffanhalv** [comment]
@tht13 Right! I did not know a request body was needed for this request. It actually did work to cancel when including the request body.

**Comment by cloveras** [comment]
Nice. We are working on better error handling, including better error messages, for this. And for a few other 500 errors. Thanks for pointing this out!
