### ISSUE TITLE
Error code 7 when launching Vipps

### ISSUE THREAD

**Issue by MatasVin** [vippsas/vipps-ecom-api#203]
Hello, I have seem to gotten a error code 7 when launching my Vipps app from my Oneplus 6 running android 10 and same issue on android 11. Do you guys have any clue what this is? Where as the error code is not on the list on the dev page (https://www.vipps.no/developers-documentation/ecom/documentation/#error-codes)

**Comment by cloveras** [comment]
HI @MatasVin 

"Error code 7" is not an error from Vipps, so I don't think we can help with this - unless you have additional information?

This may be something to contact customer service about: https://vipps.no/kontakt-oss/

Sorry for the late reply btw.

Christian, Vipps

**Comment by cloveras** [comment]
No response.
