### ISSUE TITLE
Undocumented error code 

### ISSUE THREAD

**Issue by digiloo** [vippsas/vipps-ecom-api#206]
I got the following response from a force approve, but can find the error code 1082 documented.

```
Array (
  0 => 
  (object) array(
     'errorGroup' => 'Payment',
     'errorCode' => '1082',
     'errorMessage' => '1082',
     'contextId' => '36c2eaf4-8795-4e06-bb85-ff289e640131',
  ),
)
```

/ Digiloo

**Comment by cloveras** [comment]
Hi

How did it happen? Can you please send some additional information, like orderId or contextId? And the date?

See: https://github.com/vippsas/vipps-developers/blob/master/contact.md#what-to-include-in-the-email

--
Christian, Vipps

**Comment by cloveras** [comment]
I sxee no occurences of "36c2eaf4-8795-4e06-bb85-ff289e64013" in our logs for the last 3 days in Test or Prod.

**Comment by digiloo** [comment]
MSN: 226745

Details:(object) array(
   'orderId' => '1234519123456789123456789ABC',
   'transactionLogHistory' => 
  array (
    0 => 
    (object) array(
       'amount' => 12345,
       'transactionText' => 'Mess',
       'timeStamp' => '2021-09-29T06:13:09.028Z',
       'operation' => 'INITIATE',
       'operationSuccess' => true,
    ),
  ),
)

// Digiloo

**Comment by cloveras** [comment]
I found out that you are using opur test environment.

This is the response we send for your initiate payment call:

```
{
   "orderId":"1234519123456789123456789ABC",
   "url":"https://apitest.vipps.no/dwo-api-application/v1/deeplink/vippsgateway?v=2&token=eyJraWQiOiJqd <snip>"
}
```

I also see a successful call to /details, as above:

```
{
   "orderId":"1234519123456789123456789ABC",
   "transactionLogHistory":[
      {
         "amount":12345,
         "transactionText":"Mess",
         "timeStamp":"2021-09-29T06:13:09.028Z",
         "operation":"INITIATE",
         "operationSuccess":true
      }
   ]
}
```

It seems like you make a call to `/v2/payments/1234519123456789123456789ABC/approve` next, correct?

Maybe you have missed this part from https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#testing?

> Important: All test users must manually approve at least one payment in Vipps (using the app) before "force approve" can be used for that user. This is because the user needs to be registered as "bankID verified" in the backend, and this is happens automatically in the test environment when using Vipps (the app), but not with "force approve".

I will update the documentation with some additional info.

Christian, Vipps

**Comment by digiloo** [comment]
Thanks. Yes You are right, no manual approve is done yet. But still the error code ought to be documented

/ Digiloo

**Comment by cloveras** [comment]
Yes, I have made an interrnal task for that.

**Comment by cloveras** [comment]
1082 is now documented: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#error-codes

We have an internal task for changing the "1082" `errorMessage`, but there may be more important things that must be prioritized.

**Comment by digiloo** [comment]
Ok. I understand. Thank you for super fast responses

/ Digiloo
