### ISSUE TITLE
Use of "fallback" URL is confusing

### ISSUE THREAD

**Issue by HenningKlokkeraasen** [vippsas/vipps-ecom-api#209]
The documentation mentions "fallback" URLs. These seem to not be fallback URLs at all, but main flow URLs. The use of the word "fallback" should be used only if referring to something like an error page or out of service page - things that we fall back to when something goes wrong or takes an unexpected turn.

**Comment by cloveras** [comment]
Hi @HenningKlokkeraasen 

Yes, we know. A change will require thousands of integrations to be updated, so we will have to live with this technical debt. 

It should be quite well documented, but if you have suggestions for improvements, please let is know. 

There is a new API in the works: https://github.com/vippsas/vipps-epayment-api

Christian, Vipps
