### ISSUE TITLE
Missing error types in Swagger doc

### ISSUE THREAD

**Issue by neqel** [vippsas/vipps-ecom-api#22]
In the PDF documentation version 2.1, the error response JSON representation is described under section `8. Response codes`. This type does not exist anywhere in the Swagger documentation. 

The same is true for the error type for the access token service described in section `3.2.10 Error Response Body`.

**Comment by cloveras** [comment]
Thanks! We will fix this ASAP.

**Comment by cloveras** [comment]
Oh, btw, and unrelated to Swagger: We are (gradually..) moving from PDF to Markdown: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#error-codes

**Comment by neqel** [comment]
Also, that same error response description is missing a field. Calling the API and forcing an error I see that I am actually getting:
`[
    {
        "errorGroup": "Merchant",
        "errorCode": "transaction.amount.invalid",
        "errorMessage": "Amount is invalid"
    }
]`

**Comment by cloveras** [comment]
Ai-ai! This keeps getting worse, or better 😬  I have already created an internal Jira issue, linking to this GitHub issue. Can't promise an ETA for the fix, but at least it's in the backlog.

**Comment by alfmags** [comment]
Added a better description in the swagger for responses.
