### ISSUE TITLE
Cannot redirect to checkout url

### ISSUE THREAD

**Issue by kasperaamodt** [vippsas/vipps-ecom-api#221]
Hi.

I'm setting up Vipps in my store. When I have made the token and gotten the URL, I try to redirect to it. But I get a 405 error. This is the only error message in the response header:

`x-ms-error-code: UnsupportedHttpVerb`

**Comment by cloveras** [comment]
Hello! Can you please give us some more details? See here for tips: https://github.com/vippsas/vipps-developers/blob/master/contact.md

**Comment by kasperaamodt** [comment]
Hello.

This is my API route, it tires to redirect to the URL in the response.

```
export default async function handler(req, res) {
    const { token, customerInfo, merchantInfo, transaction } = req.body;
    try {
        const headers = {
            "Content-Type": "application/json",
            Authorization: token,
            "Ocp-Apim-Subscription-Key": process.env.VIPPS_SUB_KEY_TEST,
        };
        await fetch("https://apitest.vipps.no/ecomm/v2/payments", {
            method: "POST",
            headers,
            body: JSON.stringify({
                customerInfo,
                merchantInfo,
                transaction
            })
        })
            .then((result) => result.json())
            .then((data) => {
                res.redirect(303, data.url);
            })
            .catch((err) => {});
    } catch (err) {
        const errorMessage =
            err instanceof Error ? err.message : "Internal server error";
        res.status(500).json({ statusCode: 500, message: errorMessage });
    }
}
```

I have tried 302, 303, and 307 redirects, and they all get denied.

Using test keys.

**Comment by kasperaamodt** [comment]
I haven't really worked a lot with HTTP. But from what I can gather, it looks like my API route sends the request with the OPTIONS method, and that the API does not accept OPTIONS requests, only GET. Does that sound right?

**Comment by kasperaamodt** [comment]
Dug a little more.

`OPTIONS` requests are what we call `pre-flight` requests in `Cross-origin resource sharing (CORS)`

This pre-flight request is made by some browsers as a safety measure to ensure that the request being done is trusted by the server. Meaning the server understands that the method, origin, and headers being sent on the request are safe to act upon.

But the Vipps API denies this request, and so I get the error.

**Comment by kasperaamodt** [comment]
That's okay.
