### ISSUE TITLE
AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application'

### ISSUE THREAD

**Issue by xXAvoraXx** [vippsas/vipps-ecom-api#236]
Hello, I'm trying to get access tokens on localhost but I'm getting the following error.

400 Bad Request

`{"error":"invalid_request","error_description":"AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type.\r\nTrace ID: 0c7f2993-b612-434d-9cee-244e88f51600\r\nCorrelation ID: 45d80262-c77f-487b-a95b-4566c736e1bc\r\nTimestamp: 2022-06-07 19:14:30Z","error_codes":[9002326],"timestamp":"2022-06-07 19:14:30Z","trace_id":"0c7f2993-b612-434d-9cee-244e88f51600","correlation_id":"45d80262-c77f-487b-a95b-4566c736e1bc","error_uri":"https://login.windows.net/error?code=9002326"}`

```
  async getVippsAccessToken() {
    const msg = await request<VippsAccessTokenResponse>(`/vipps/accesstoken/get`, {
      method: 'POST',
      prefix: undefined,
      credentials: 'include',
      headers: {
        client_id: this.client.client_id,
        client_secret: this.client.client_secret,
        'Ocp-Apim-Subscription-Key': this.client['Vipps-Subscription-Key'],
        'Merchant-Serial-Number': this.client['Merchant-Serial-Number']!,
        'Vipps-System-Name': 'myapp',
        'Vipps-System-Version': '1',
        'Vipps-System-Plugin-Name': 'myapp-externalPayment',
        'Vipps-System-Plugin-Version': '1',
      },
    });

    return msg;
  }
-----------------------------
Proxy
    '/vipps': {
      target: 'https://apitest.vipps.no',
      changeOrigin: true,
      secure: false,
      pathRewrite: { '^/vipps': '' },
    },
```

**Comment by cloveras** [comment]
Hi

Please see the FAQ: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-faq.md#why-do-i-get-a-cors-error

**Comment by xXAvoraXx** [comment]
> Hi
> 
> Please see the FAQ: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-faq.md#why-do-i-get-a-cors-error
> 
> > Why do I get a CORS error?
> > If you get a CORS (Cross-Origin Resource Sharing) error, it is from your side, not an error from Vipps. You are most likely attempting to call the Vipps API from a website, and your webserver's configuration prevents it.
> > CORS is a protocol that enables scripts running on a browser client to interact with resources from a different origin. Sometimes servers are configured to prevent this, and that results in a CORS error.
> > Vipps only receives the API requests over HTTPS, and has no way of detecting how the request was made on the caller side - it all looks the same. We can not fix the CORS error for you.
> > You can read more about CORS here: [CORS Tutorial: A Guide to Cross-Origin Resource Sharing](https://auth0.com/blog/cors-tutorial-a-guide-to-cross-origin-resource-sharing/).

I created a proxy to solve the Cors problem, I allowed cross origin, when I send a request to the vipps api without headers, it returns 401, but when I add the headers, I get this error. I could not provide a solution.

**Comment by xXAvoraXx** [comment]
I could'nt solve this problem, Do I need to write something to the test api from here? https://portal.vipps.no/

**Comment by cloveras** [comment]
As mentioned, the error is on your side. We can not offer more help with this than what we have documented above.
