### ISSUE TITLE
AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application'

### ISSUE THREAD

**Issue by xXAvoraXx** [vippsas/vipps-ecom-api#246]
I got this error "AADSTS9002326" when I request to apitest.vipps.no.

You need to look at the solution for this error.
[Solution](https://github.com/Intility/fastapi-azure-auth/issues/47)

I've been dealing with this issue for weeks now, by setting up a proxy on my own server, I've forwarded the requests and solved the cross-origin issue. The error I get can be fixed by you.

https://stackoverflow.com/questions/72575793/aadsts9002326-cross-origin-token-redemption-is-permitted-only-for-the-single-p

https://issuehint.com/issue/Azure-Samples/ms-identity-javascript-angular-tutorial/37

`{"error":"invalid_request","error_description":"AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type.\r\nTrace ID: 578a738f-3b77-4a4b-a425-160f38da2d00\r\nCorrelation ID: cabc0d01-da8d-4b44-90b8-b182c1f21e1b\r\nTimestamp: 2022-07-03 18:51:58Z","error_codes":[9002326],"timestamp":"2022-07-03 18:51:58Z","trace_id":"578a738f-3b77-4a4b-a425-160f38da2d00","correlation_id":"cabc0d01-da8d-4b44-90b8-b182c1f21e1b","error_uri":"https://login.windows.net/error?code=9002326"}`

**Comment by xXAvoraXx** [comment]
@cloveras 

https://github.com/dotnet/AspNetCore.Docs/issues/24594#issuecomment-1013063562

**Comment by cloveras** [comment]
HI. I hope you found the problem and fixed it, so I'm closing this issue now.
