### ISSUE TITLE
Documentation  "Direct capture", missing information

### ISSUE THREAD

**Issue by Gogoro** [vippsas/vipps-ecom-api#32]
Hello!

I'm woking on an integration to this API, and want to use the "Direct capture" functionality. But I can't seam to find a good _description_ on how to utilize it.

In the documentation it says:

> Direct capture is not depicted on diagram above but, in essence, combines two steps (reserve and
capture) in one. This is a configuration in Vipps backend when Initiate payment request is sent. 

I understand this as there being a way to initiate the payment request with a "flag" of some sort saying "directCapture". 

Any way someone could help me out here? And maybe update the documentation with a description on how to use this?

**Comment by cloveras** [comment]
Hi, @Gogoro - and thanks for pointing this out!

Direct capture is done automatically, after a configuration change in the Vipps backend. A customer can not select between "normal capture" and "direct capture".

Updating the documentation is a good idea, and I already made a small change: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#regular-ecommerce-payments

Is this ok, or should can we improve it?

There is some information in the FAQ too: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-faq.md#what-is-the-difference-between-reserve-capture-and-direct-capture-and-how-do-i-change-payment-type

Christian, Vipps

**Comment by Gogoro** [comment]
Hi, and 🥇 for the quick reply @cloveras!

The clarification made it super obvious that it's nothing I can "implement" myself 👍 Thank you!

I'll ask to get it enabled via email.

Have a great day!
