### ISSUE TITLE
Deep link with test APP

### ISSUE THREAD

**Issue by Gogoro** [vippsas/vipps-ecom-api#33]
Hi!

I'm working on integrating the Vipps payment flow into my app and just hit a wall with deep links.

When I initiate a new payment with "isApp: true" i get a link back like this: `vipps://?token=...`. This opens the production version of the Vipps app, but when I'm working in test, it should go to the test version.

Do you guys have any trick I can to to make it go to the "test" app? Ex replace `vipps:// `with the scheme of the test app? If so, what is it? 😄 

Ps: I'm working on the iOS versjon of the app right now.

Cheers,
Ole

**Comment by cloveras** [comment]
Hi, @Gogoro 

The URL is the same for the App Store app as for the TestFlight app. No trick to open a specific one, unfortunately.

Now added to https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#switch-from-merchant-app-to-the-vipps-app

> Please note: If you have both the official Vipps app from App Store and the test Vipps app from TestFlight installed, the app switch may open either one. There is no way to open one of them specifically, as the URL scheme is the same for both. A workaround is to only have one of the apps installed on the device.

Christian, Vipps

**Comment by Gogoro** [comment]
Hi @cloveras, and thanks again for the quick reply!

I deleted the "production" version of Vipps from my phone and it worked like a charm. 

Cheers,
Ole
