### ISSUE TITLE
Requests should have headers too

### ISSUE THREAD

**Issue by cloveras** [vippsas/vipps-ecom-api#36]
All requests under "Complete HTTP requests and responses for each API endpoint and method" should have headers (possibly with tokens truncated for readability):

https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#complete-http-requests-and-responses-for-each-api-endpoint-and-method

**Comment by acccentor** [comment]
Added request headers for initiate payment requests. Joel argued that it would be cluttering to add more than that.
