### ISSUE TITLE
Transaction Update Callback enpoint is missing /ecomm in swagger doc and pdf doc

### ISSUE THREAD

**Issue by annemsa75** [vippsas/vipps-ecom-api#39]
Found this in the pdf documentation and swagger doc:
[callbackPrefix]/v2/payments/{orderId}

**Comment by acccentor** [comment]
Sorry, this was an early mistake in our documentation that is being removed. As the merchant endpoint is not provided by ecom, they should not contain /ecomm. The correct path for merchant endpoints starts with /v2.
