### ISSUE TITLE
Feil objekt returneres i Refund kall

### ISSUE THREAD

**Issue by Doff3n** [vippsas/vipps-ecom-api#48]
I dokumentasjonen står det at det returneres "TransactionInfo" i refund kallet:
https://github.com/vippsas/vipps-ecom-api/blob/dc8b8f85dcfbb84b413e5869b2dffd001d72e379/docs/swagger.json#L1261

I realiteten returneres "Transaction".

API burde oppdateres til å reflektere dokumentasjon, jeg hadde forventet å få TransaksjonInfo tilbake her slik som i de andre kallene. 

Eventuelt så burde dokumentasjonen oppdateres til å reflektere det faktiske svaret som kommer tilbake.

**Comment by cloveras** [comment]
Hei, @Doff3n

Takk for at du sier fra! Denne lille fadesen er nå rettet. 

Christian, Vipps
