### ISSUE TITLE
authToken is missing

### ISSUE THREAD

**Issue by sjelfull** [vippsas/vipps-ecom-api#49]
`authToken` is missing/unclear in several places.

- There is no explanation of the function of it (it's hidden in the model in Swagger)
- There is no example in the callbacks

**Comment by cloveras** [comment]
Thanks for reporting this, @sjelfull

We will imperove the documentation for this:
* Description and request example in the Markdown guide
* Proper documentation in Swagger

Christian, Vipps

**Comment by acccentor** [comment]
Details related to `authToken` was added to swagger and markdown guide.
