### ISSUE TITLE
Callback example for regular checkout

### ISSUE THREAD

**Issue by sjelfull** [vippsas/vipps-ecom-api#50]
`expressCheckOutPaymentRequest` is listed in the Swagger docs, but I can't find a way to see the regular callback payload?

**Comment by cloveras** [comment]
Hi @sjelfull 

Thanks for the feedback, we will add this.

Christian, Vipps

**Comment by acccentor** [comment]
Regular callback is now added using oneOf and OpenAPI callbacks.
