### ISSUE TITLE
Custom displayed order id

### ISSUE THREAD

**Issue by sjelfull** [vippsas/vipps-ecom-api#51]
Would there be a way to have the displayed order id be different from the internal `{orderId}` used for all other purposes?

The `orderId` in our system might be a really long uuid, but ideally I'd like to show something more friendly in the app.

**Comment by cloveras** [comment]
Hi @sjelfull 

As mentioend in the other channel, we have no specific plans to change this. If the internal id is too long to display in the app, a possible workaround is to map it to a or user-friendly id in the app. Of course, the `transactionText` should also be used:

```
{
  "customerInfo": {
    "mobileNumber": 91234567
  },
  "merchantInfo": {
    "authToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1Ni <snip>",
    "callbackPrefix": "https://example.com/vipps/callbacks",
    "consentRemovalPrefix": "https://example.com/vipps",
    "fallBack": "https://example.com/vipps/fallback/order123abc",
    "isApp": false,
    "merchantSerialNumber": 123456,
    "paymentType": "eComm Regular Payment",
    "shippingDetailsPrefix": "https://example.com/vipps/shipping/"
  },
  "transaction": {
    "amount": 20000,
    "orderId": "order123abc",
    "refOrderId": "merchantOrder123abc",
    "timeStamp": "2018-11-14T15:44:26.590Z",
    "transactionText": "One pair of Vipps socks"
  }
}
```

https://vippsas.github.io/vipps-ecom-api/#/Vipps_eCom_API/initiatePaymentV3UsingPOST

Christian, Vipps

**Comment by abraham-fox** [comment]
@cloveras, If custom order Id doesn't support by API, then maybe there is some method to hide OrderId field completely for an end user? I think I saw Vipps App UI without order id at some webshop.

**Comment by cloveras** [comment]
Hi, @abraham-fox 

There is no (known) way to hide an `orderId`, but we recommewnd using a self-explanatory `transactionText`. I have just updated the documentation to specify that the limit is 100 characters.

Christian, Vipps
