### ISSUE TITLE
Allow local fallback URL

### ISSUE THREAD

**Issue by zaporylie** [vippsas/vipps-ecom-api#54]
Fallback URL doesn't have to be publicly available. It must only be reachable from browser that initiates payment.

**Comment by cloveras** [comment]
Hi, and thanks for reporting this! 

We are looking into it, sorry for not updating here earlier. We may not be able to validate URLs differently, but we are certainly going to check.

Christian, Vipps

**Comment by cloveras** [comment]
Hi

Sorry for the extremely late reply.

We use the same validation for all externally provided URLs, and can not prioritize implementing support for local URLs, sorry.

Christian, Vipps
