### ISSUE TITLE
Feature request: Transaction timeout

### ISSUE THREAD

**Issue by peters** [vippsas/vipps-ecom-api#57]
Allow a merchant to specify an expiry date for a given transaction instead of today's hard coded limit of 4 minutes.

**Comment by cloveras** [comment]
Hi, @peters 

Thanks for suggesting this, and sorry for the very late reply. The number of GitHub notifications made this one slip past, and we will try to check here more often.

The expiry time was recently changed to five minutes. Our statiustics show that this makes it work for around 90 % of the users who did not make it in time when the limit was 4 minutes.

Letting merchabnts specify a timeout adds a lot of additional complexity, which is hard to justify agains all other development efforts, so we will stick with 5 minutes. Extending to , say, 7 minutes would make it work for even more customers, but it would also require merchants to reserve good for a longer time, which is problematic during sales campaigns with high traffic, such as "Black Friday".

Christian, Vipps
