### ISSUE TITLE
Add shippingMethodId to Transaction Update callback response and Get Payment Details

### ISSUE THREAD

**Issue by zaporylie** [vippsas/vipps-ecom-api#59]
shippingDetails callback requires both `shippingMethod` and `shippingMethodId` to be set. But when Payment is completed only `shippingMethod` is available in:
- Transaction Update callback response
- Get Payment Details resource

Multiple shipping methods can have identical `shippingMethod` so `shippingMethodId` is mandatory to determine which method customer selected.

**Comment by zaporylie** [comment]
Seems like it's only lacking from the documentation, but the property is actually available in json when querying Get Payment Details resource.

**Comment by tht13** [comment]
@zaporylie Thanks for reporting this 😃
