### ISSUE TITLE
Error in Address model documentation - zipCode vs postCode

### ISSUE THREAD

**Issue by zaporylie** [vippsas/vipps-ecom-api#60]
`Address` model documentation uses `zipCode` field while the field available in the response has `postCode` property, rather than `zipCode`.

Compare https://github.com/vippsas/vipps-ecom-api/blob/9ac4024f9f2fd1b34df39c708c74a382cbc2fd3f/docs/swagger.yaml#L809-L812
with
```
{"address": {"addressLine1":"a","addressLine2":"b","postCode":"1234","city":"c","country":"Norway"}
```

**Comment by ananthb86** [comment]
Updated the documentation. Thank you for reporting this.

**Comment by JensEgilEvensen** [comment]
This issue is not resolved
The property name on the address class differs from different services. GetPaymentDetails returns postCode and InitiatePayment.... returns zipCode. The two methods must either return the same object graph for address, or utilize different Address classes

**Comment by cloveras** [comment]
Hi, @JensEgilEvensen 

I'm sorry for us not noticing the last comment here until now! 🙈 

We are aware of the two addresses being different, and we _would_ like to change it, but unfortunately we have more pressing issues, and we can not prioritise this. A change would also, most likely, not be backwards compatible, and require changes to existing integrations. See the (in-progress) [API lifecycle](https://github.com/vippsas/vipps-developers/blob/master/vipps-api-lifecycle.md).

So, our best solution is to do our best to document the API as it is today, and strive to do better in the future.

New APIs, such as the [Recurring API](https://github.com/vippsas/vipps-recurring-api), have been developed according to common API guidelines, and should result in less frequent WTFs.

Christian, Vipps
