### ISSUE TITLE
InitiatePaymentV3UsingPOSTAsync does not handle http response 200

### ISSUE THREAD

**Issue by JensEgilEvensen** [vippsas/vipps-ecom-api#67]
The generated proxy-class from swagger does not deserialize the response data into an object if the response status is 200 (OK). It only returns default(InitiatePaymentV2Representation) which is NULL

**Comment by tht13** [comment]
Hi, 
Can you confirm which language you are generating into here?

Thanks

**Comment by tht13** [comment]
After investigating its because the swagger defines the response as 202, whereas it should be 200. This is a bug and we will fix this.

**Comment by JensEgilEvensen** [comment]
C# asp.net core 2.2

**Comment by tht13** [comment]
Can you test against the new swagger file @niklud updates in 078a885a to confirm the fix?
