### ISSUE TITLE
Onboarding process does only give access to API V2. Auth API + API V1 is missing.

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-ecom-api#77]
Hi! 😁

We are now implementing two new checkout integrations for a customer and have started the onboarding process using this scheme: https://vippsbedrift.no/signup/vippspanett/ & we are happy to see that the keys is now to be found at portal.vipps.no instead of the old interface which we found hard to work with.

So the request has been approved, but some API keys is still missing.

**1st:**
We can see the **Vipps-eCommerce-Services** product in the list which has:

- Merhcant ID
- Client ID
- Client Secret
- Primary key
- Secondary key

But, we do not have access to the auth token API and we can't find the Primary Key for the auth api anywhere. 😱 (**Edit:** I refer to the JWT access token, see image in the first comment below)

This is also the case for previous integrations where we already have the codes. All codes and products is displayed in the list except for the Primary Key for the auth / token service. Without this code it is not possible to use any endpoints, because you cant generate an access token without it.

For the companies we previously integrated with vipps we do at least find the **eCommerce-Classic-Services** in the list which is good.

**In summary:**

At the onboarding process you should not only give access to the API V2, but also the Auth API and API V1 **by default / always**.

**Why Auth API?**
API V2 can't be used without the Auth API. (**Edit:** Here I ment the JWT Access token. It looks like it is supposed to be available on the portal some where, but I cant find it.)

**Why API V1 (classic)?**
Checkout with V2 _REQUIRES a BROWSER_ and that the customer leaves the shop / app.
This means that it will not work with certain software where a web browser is not intended (as in our use case). (**Edit:** I now see that this is deprecated, ref. screenshot in first comment. That is not good news for us, so I created a new issue on it. -> https://github.com/vippsas/vipps-ecom-api/issues/78)

When using API V1 (classic) this is not a problem, but _with V2 it is a problem_.
For example - We use it for a "Self service POS". and don't want to add a web-browser to it (neither a popup / iframe).

I also send this by e-mail to integration@vipps.no

**Comment by steffanhalv** [comment]
What I am reffering to is the JWT token - Ref.
![Skjermbilde 2019-10-18 kl  15 17 20](https://user-images.githubusercontent.com/4593184/67097645-d3bb7680-f1ba-11e9-9f30-fecf17f3ab1e.png)

I did also found that API V1 is deprecated which is also not good, so I create another issue for that - Ref.
![Skjermbilde 2019-10-18 kl  15 13 44](https://user-images.githubusercontent.com/4593184/67097704-f188db80-f1ba-11e9-8c3c-b2014828b049.png)

**Comment by cloveras** [comment]
Hi

The API products have been merged and simplified, please see: https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md#api-products

The JWT is fetched as documented here: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#access-token

The whole flow with requests and responses can be seen in the Postman collection and Python example code, available from https://github.com/vippsas/vipps-ecom-api

Hope this (and the reply to the email with reference to this and the other issue) helps.

Christian, Vipps

**Comment by steffanhalv** [comment]
Thank you that helped me out!

We got everything to work by using the same codes :)
