### ISSUE TITLE
Deprecation of API V1 causing trouble because of missing functionality in V2

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-ecom-api#78]
I just logged in to the old portal and found this (says API V1 is deprecated):

![Skjermbilde 2019-10-18 kl  15 13 44](https://user-images.githubusercontent.com/4593184/67098905-475e8300-f1bd-11e9-934f-f7b34b624178.png)

**Why this is a problem**
Many of our integrations is heavily based on it because it has a feature which is not supported in API v2. It will cause trouble for multiple systems which has been live for already over a year & also upcoming projects which is still in the developer stage and soon ready to be published.

**The missing functionality in V2**
The functionality I am referring to is the following endpoint:

POST request to https://api.vipps.no/Ecomm/v1/payments

**What V1 does**
It initiates the payment process right away which is perfect. 🤗
The user can just open the App and accept!

**What V2 does**
It returns a link which customer has to follow (Either a webbrowser link or a deeplink.) 🤔
The user has to go to another page and click another button.

**Good with V1**
It doesn't require a browser to initiate the payment, but it can be directly initiated from any app or payment service application. The initiation requires one less step and is faster on the web! (when not using mobile deeplink).

**Bad with V1**
It does not have the option with deeplink for mobile.

**Good with V2**
It has the option for deeplinking on mobile devices (Express checkout).

**Bad with V2**
It removes the option for customized payment initiation triggers.
It requires the user to follow the link.
It is slower (Express checkout is true for mobile deeplink, but false for desktop checkout).
It will make some systems stop working when V1 is removed and scratch some ongoing projects for us at least

Hope you can help out our frustrations 😅

**Comment by cloveras** [comment]
Hi

The API products have been merged and simplified see: https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md#api-products

The API products and the APIs are different.

We have no specific plans to disable the eCom v1 API.

See also the reply to #77 (and the reply to the email about the same issues).

Christian, Vipps

**Comment by steffanhalv** [comment]
Ok, thank you. But what about this notice (see marked selection):

Ref. https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md#vipps-api
![Skjermbilde 2019-10-19 kl  20 14 19](https://user-images.githubusercontent.com/4593184/67149576-1cebf300-f2ad-11e9-9309-4e8108309c34.png)

**Comment by cloveras** [comment]
Hi

It will, at some point, be phased out, but we have no specific plan yet. 

When v1 is phased out, we will of course offer a better solution, as well as sufficient time to upgrade. 

We plan to pilot our new in-store solution later this year, and that will be our mann solution for POS integrations.

Christian, Vipps

**Comment by steffanhalv** [comment]
Sounds good!
