### ISSUE TITLE
Documentation quality - some thoughts

### ISSUE THREAD

**Issue by jbjorge** [vippsas/vipps-ecom-api#87]
I've had a hard time integrating Vipps into some products. It is solely because of how the documentation is structured. It seems kind of like... a mess.

When I read documentation for services, I'm used to it being written with a perspective that helps me achieve my goals.

The documentation I've found for Vipps integration seems like it's just a knowledge dump with little to no structure.
It does not display a clear path to achieving the end goals for integrators (e.g. "steps to integrate for android", "steps for integrating with a web project", etc.) and it uses terms without ever explaining what they mean.

I'm sorry to say it, but something that could have taken 30 minutes to implement ended up taking days due to the documentation (and I've heard others have spent way more than that).

The documentation is currently 34 pages long (A4).
The parts I ended up using for a web integration could probably have been condensed down to three pages.

**Comment by cloveras** [comment]
Hi, and thanks for taking the time to give feedback!

We are aware that the eCom API documentation still needs work, and the ambition is to have one common template/ToC for all externally available APIs, and update all guides according to this. 

Having said that, we have improved the documentation significantly. Last year we only had some more or less outdated PDFs, now we have comprehensive (although not perfectly structured) API guides,  Swagger specifications, Postman collections, FAQs, integration checklists, example code, etc. We also have open source plugins for WooCommerce, Magento, Drupal - and soon also for Episerver, Drupal and Shopify.

I was not aware that the eCom API guide was 34 pages, but it is not intended for printing. We make frequent improvements and updates, based on input from developers. Just today we have added guidelines for how frequently to poll the `/details` endpoint. There is a table of contents, so it should be reasonably easy to find the right section.

For a very quick intro to the API, the first items in the checklist here may be useful: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api-checklist.md

The flow diagram in the API guide should also work as an ok intro: https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#flow-diagram

If you have specific suggestions for what to improve, please let us know, and we will do our best to help.


Christian, Vipps

**Comment by cloveras** [comment]
Hei igjen

Ser at du har forket repoet, og vil bare tipse om at du foreløpig er 11 commits etter master: https://github.com/jbjorge/vipps-ecom-api

Siste commits: https://github.com/vippsas/vipps-ecom-api/commits/master/vipps-ecom-api.md

Dette støtter forsåvidt opp under det du skriver om at det stadig legges til informasjon, men _helt_ uten struktur er det jo ikke, selv om vi en gang må stramme opp hele guiden, både for eCom og andre API-er.

Christian, Vipps

**Comment by cloveras** [comment]
Hello once again (this time in English again)

Here's a branch of the API guide with quite a bit of restructuring. Still a work in progress, but hopefully it's an improvement:

https://github.com/vippsas/vipps-ecom-api/blob/restructuring/vipps-ecom-api.md


Christian, Vipps

**Comment by cloveras** [comment]
PR: https://github.com/vippsas/vipps-ecom-api/pull/89

**Comment by cloveras** [comment]
PR merged, and since there is little activity here, I will close this issue. I hope the API guide is better now! 😅
