### ISSUE TITLE
Localhost as fallback

### ISSUE THREAD

**Issue by joakimkm** [vippsas/vipps-ecom-api#98]
Documentation says: _"URLs that start with https://localhost will be rejected. If you want to use localhost as fallback, please use http://127.0.0.1"_, but this do not work.
When fallBack is set to "http://127.0.0.1/vipps/complete/useridabc123" error response is randomly changing between this two responses:
`[
    {
        "errorGroup": "Merchant",
        "errorCode": "Invalid IP address",
        "errorMessage": "Invalid IP address",
        "contextId": "6f90fd24-465d-469f-9288-8b8b7003dc3d"
    }
]`
and sometimes
`
[
    {
        "errorGroup": "Merchant",
        "errorCode": "{merchantInfo.fallback.URL.IPAddress.invalid}",
        "errorMessage": "{merchantInfo.fallback.URL.IPAddress.invalid}",
        "contextId": "6699dcf9-d8e4-4946-94cc-ca9e8900c71d"
    }
]
`
I am using API-keys for VIPPS test environment.

**Comment by cloveras** [comment]
Hi @joakimkm 

Thanks for letting us know. We have fixed the problem, and 127.0.0.1 now works again.

Christian, Vipps

**Comment by CraigAndrew** [comment]
Hi There, this issue is happening again on VIPPS Test Environment.
Getting a 400 response for my requests with error:
    {
        "errorGroup": "Merchant",
        "errorCode": "Invalid IP address",
        "errorMessage": "Invalid IP address",
        "contextId": "ed9f848e-8a76-4d66-ac75-c1df9d011fa3"
    }

when the URLs in the request start with http://127.0.0.1
e.g: http://127.0.0.1/vipps/payment/done/123

**Comment by michalzubrzycki** [comment]
Problem showed up again on test env. Logs from my app after settings fallback URL to http://127.0.0.1
`[2021-06-11T12:43:16] local.ERROR: Code: 400, Message: {merchantInfo.callbackPrefix.URL.IPAddress.invalid}
[2021-06-11T12:43:27] local.ERROR: Code: 400, Message: Invalid IP address
[2021-06-11T12:43:35] local.ERROR: Code: 400, Message: Invalid IP address
[2021-06-11T12:43:45] local.ERROR: Code: 400, Message: {merchantInfo.callbackPrefix.URL.IPAddress.invalid}
[2021-06-11T12:43:57] local.ERROR: Code: 400, Message: {merchantInfo.callbackPrefix.URL.IPAddress.invalid}`
